name: Python Unittest

on:
  workflow_call:
    inputs:
      requirements:
        required: false
        type: string
        default: -r requirements.txt
      pythonpath:
        required: false
        type: string
        default: src
      discover-syntax:
        required: false
        type: string
        default: 'test_*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: unit-tests
        run: |
          pip3 install ${{ inputs.requirements }}
          pip3 install coverage
          export PYTHONPATH="$PYTHONPATH:${{ inputs.pythonpath }}"
          coverage run -m unittest discover -s ./tests -p ${{ inputs.discover-syntax }}
          coverage report -m